# Cloud Build configuration for Pokemon Card Scanner
# This allows for automated builds and deployments via Google Cloud Build

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-f'
      - 'Dockerfile.cloudrun'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:$COMMIT_SHA'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:latest'
      - '.'
    id: 'build-image'

  # Step 2: Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:$COMMIT_SHA'
    id: 'push-image-sha'
    waitFor: ['build-image']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:latest'
    id: 'push-image-latest'
    waitFor: ['build-image']

  # Step 3: Deploy to Cloud Run (only on main branch)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}:$COMMIT_SHA'
      - '--platform=managed'
      - '--region=${_REGION}'
      - '--allow-unauthenticated'
      - '--port=80'
      - '--memory=1Gi'
      - '--cpu=1'
      - '--timeout=300'
      - '--concurrency=10'
      - '--min-instances=0'
      - '--max-instances=3'
      - '--set-env-vars=ENVIRONMENT=test,DEBUG=false,LOG_LEVEL=INFO,SERVE_STATIC_FILES=true,ENABLE_API_DOCS=true'
      - '--set-secrets=GOOGLE_API_KEY=GOOGLE_API_KEY:latest,POKEMON_TCG_API_KEY=POKEMON_TCG_API_KEY:latest'
    id: 'deploy-cloud-run'
    waitFor: ['push-image-sha']

# Substitution variables
substitutions:
  _REGION: 'us-central1'
  _REPOSITORY: 'pokemon-scanner'
  _IMAGE_NAME: 'pokemon-card-scanner'
  _SERVICE_NAME: 'pokemon-scanner-test'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'
  substitution_option: 'ALLOW_LOOSE'
  logging: 'CLOUD_LOGGING_ONLY'

# Build timeout (increased for AI model dependencies)
timeout: '1200s'

# Required IAM permissions for Cloud Build service account:
# - Cloud Run Admin
# - Artifact Registry Writer
# - Secret Manager Secret Accessor