version: '3.8'

services:
  pokemon-scanner:
    build: .
    ports:
      - "8000:8000"
    environment:
      # Core API Configuration (required)
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - POKEMON_TCG_API_KEY=${POKEMON_TCG_API_KEY}
      
      # Server Configuration
      - HOST=0.0.0.0
      - PORT=8000
      - ENVIRONMENT=development
      - DEBUG=true
      
      # Logging
      - LOG_LEVEL=INFO
      - ENABLE_API_DOCS=true
      
      # Security
      - CORS_ORIGINS=*
      
      # Error Webhooks (optional for development)
      - ERROR_WEBHOOK_ENABLED=false
      
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/api/v1/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # Optional: Mount source code for development (uncomment for live reload)
    # volumes:
    #   - ./src:/app/src:ro
    
    # Optional: Add development command with auto-reload (uncomment for development)
    # command: ["uvicorn", "src.scanner.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

# Optional: Add a reverse proxy for production-like setup
# nginx:
#   image: nginx:alpine
#   ports:
#     - "80:80"
#   volumes:
#     - ./nginx.conf:/etc/nginx/nginx.conf:ro
#   depends_on:
#     - pokemon-scanner