version: '3.8'

services:
  pokemon-scanner:
    build: .
    ports:
      - "8000:8000"
    environment:
      # Required: Google API key for Gemini
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      
      # Optional: Pokemon TCG API key for higher rate limits
      - POKEMON_TCG_API_KEY=${POKEMON_TCG_API_KEY:-}
      
      # Server configuration
      - HOST=0.0.0.0
      - PORT=8000
      
      # Processing options
      - OPTIMIZE_FOR_SPEED=true
      - MAX_IMAGE_DIMENSION=1024
      - ENABLE_COST_TRACKING=true
      
      # Rate limiting
      - MAX_REQUESTS_PER_MINUTE=60
      - ENABLE_CACHING=true
      - CACHE_TTL_SECONDS=3600
    
    volumes:
      # Mount logs directory for persistence
      - ./logs:/app/logs
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/api/v1/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # Mount SSL certificates if available
    depends_on:
      - pokemon-scanner
    restart: unless-stopped
    profiles:
      - production  # Only start with --profile production