version: '3.8'

services:
  pokemon-scanner-api:
    build:
      context: .
      target: production
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - POKEMON_TCG_API_KEY=${POKEMON_TCG_API_KEY:-}
      - ENVIRONMENT=production
      - DEBUG=false
      - LOG_LEVEL=INFO
      - SERVE_STATIC_FILES=false
      - ENABLE_API_DOCS=true
      - CORS_ORIGINS=${CORS_ORIGINS:-*}
      - RATE_LIMIT_PER_MINUTE=100
      - CACHE_ENABLED=true
      - ENABLE_METRICS=true
      - METRICS_PORT=9090
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G
    volumes:
      - api_logs:/app/logs
    networks:
      - api-network

networks:
  api-network:
    driver: bridge

volumes:
  api_logs: