apiVersion: v1
kind: Secret
metadata:
  name: pokemon-scanner-secrets
  namespace: pokemon-scanner
type: Opaque
stringData:
  # Required: Replace with your actual API keys
  GOOGLE_API_KEY: "your-gemini-api-key-here"
  POKEMON_TCG_API_KEY: "optional-tcg-api-key"
  
  # Error Notification Hooks (optional)
  ERROR_WEBHOOK_URL: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
  ERROR_WEBHOOK_ENABLED: "false"
  ERROR_WEBHOOK_TIMEOUT: "10"
  ERROR_WEBHOOK_MIN_LEVEL: "ERROR"
  ERROR_WEBHOOK_INCLUDE_TRACEBACK: "true"
  ERROR_WEBHOOK_RATE_LIMIT: "5"
  ERROR_WEBHOOK_ENVIRONMENT_TAG: "production"